name: StitchCraft
main: me.Nekoyoubi.StitchCraft.StitchCraft
version: 0.2
commands:
  stitchcraft:
    description: Displays information about StitchCraft.
    usage: /<command>
    aliases: sc
  autotorch:
    description: Toggles automatic torch placement.
    usage: /<command> [light level]
    aliases: at
